version: 1
services:
  - type: web
    name: gr0k-dm-migrate
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npx drizzle-kit push
    envVars:
      DATABASE_URL:
        fromDatabase:
          databaseName: gr0k_dm_db
          property: connectionString
