version: 1
services:
  - type: web
    name: gr0k-dm-migrate
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npx drizzle-kit push
    envVars:
      DATABASE_URL: postgresql://gr0k_dm_db_user:GxPuNrlcUlfZEHImr8m7bMu6B3NuBbdz@dpg-d4ra7i7pm1nc73bjqtlg-a/gr0k_dm_db 
          property: connectionString
